apiVersion: v1
kind: Pod
metadata:
  name: whenever
spec:
  containers:
  - image: ernoaapa/whenever:latest
    name: whenever
    args:
      # Watch this directory recursively
      - /config
      # Execute this command
      - cat /config/msg.txt
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
    - name: config
      configMap:
        name: my-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  msg.txt: Hello world!
